#!/usr/bin/env python 

#
from sys import argv
step = int(argv[1].split('/')[1])

# Write
with open('ckpt/{}/checkpoint'.format(step), 'w') as f:
    f.write('model_checkpoint_path: "model.ckpt-{}"\n'.format(step))
    f.write('all_model_checkpoint_paths: "model.ckpt-{}"'.format(step))

from os import environ
from subprocess import call
environ['CUDA_VISIBLE_DEVICES']=''
call('dp freeze', shell=True, cwd='ckpt/{}/'.format(step))

call('mkdir {}'.format(step), shell=True)
call('cp -n ckpt/{}/frozen_model.pb {}'.format(step, step), shell=True)
